# Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras.callbacks import ModelCheckpoint

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=["EIN"], axis=1, inplace=True)

In [3]:
# Determine the number of unique values in each column.
application_df.value_counts()

NAME                                                            APPLICATION_TYPE  AFFILIATION       CLASSIFICATION  USE_CASE      ORGANIZATION  STATUS  INCOME_AMT   SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL
PARENT BOOSTER USA INC                                          T3                CompanySponsored  C2100           Preservation  Trust         1       0            N                       5000     0                887
TOPS CLUB INC                                                   T3                CompanySponsored  C1200           Preservation  Association   1       0            N                       5000     0                672
UNITED STATES BOWLING CONGRESS INC                              T3                CompanySponsored  C1000           Preservation  Trust         1       0            N                       5000     0                583
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                 T3                CompanySponsored  C1200           Preservation  Trust         1       0            N                       5000     0                319
WASHINGTON STATE UNIVERSITY                                     T3                CompanySponsored  C2000           Preservation  Trust         1       0            N                       5000     0                318
                                                                                                                                                                                                                      ...
GFWC BJWC INC                                                   T3                Independent       C1000           Preservation  Trust         1       0            N                       5000     1                  1
GEV INC                                                         T3                Independent       C1000           Preservation  Trust         1       1-9999       N                       5000     1                  1
GETHSEMANE SHRINE NO 79 ORDER OF THE WHITE SHRINE OF JERUSALEM  T8                Independent       C1000           Preservation  Association   1       0            N                       5000     0                  1
GET THERE ATHLETICS                                             T3                Independent       C1000           Preservation  Trust         1       25000-99999  N                       10202    0                  1
ZURICH PUBLISHING FOUNDATION INC                                T3                Independent       C2000           Preservation  Trust         1       0            N                       5000     1                  1
Name: count, Length: 22396, dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_value_counts = application_df["APPLICATION_TYPE"].value_counts()
application_value_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`  classification_value_counts[classification_value_counts < 1880].index[:].tolist()
application_types_to_replace = application_value_counts[application_value_counts < 800].index[:].tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_value_counts = application_df['CLASSIFICATION'].value_counts()
classification_value_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts(dropna=False)[application_df["CLASSIFICATION"].value_counts(dropna=False) > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_value_counts[classification_value_counts < 1880].index[:].tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# view values counts for name column
name_value_counts = application_df["NAME"].value_counts()

In [11]:
# drop lowest value to better visualize data
application_df['NAME'].value_counts(dropna=False)[application_df["NAME"].value_counts(dropna=False) > 2]

NAME
PARENT BOOSTER USA INC                                             1260
TOPS CLUB INC                                                       765
UNITED STATES BOWLING CONGRESS INC                                  700
WASHINGTON STATE UNIVERSITY                                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                     408
                                                                   ...
ENTREPRENEURS ORGANIZATION                                            3
CENTER FOR THE STUDY OF CLASSICAL ARCHITECTURE INC                    3
VETERANS OF FOREIGN WARS OF THE UNITED STATES DEPT OF TENNESSEE       3
AMERICAN MARKETING ASSOCIATION INC                                    3
UNITED STATES BOWLING CONGRESS                                        3
Name: count, Length: 577, dtype: int64

In [12]:
# Choose a cutoff value and create a list of names to be replaced
# use the variable name `names_to_replace`
names_to_replace = name_value_counts[name_value_counts < 300].index[:].tolist()

# Replace in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure replacement was successful
application_df['NAME'].value_counts()

NAME
Other                                              29662
PARENT BOOSTER USA INC                              1260
TOPS CLUB INC                                        765
UNITED STATES BOWLING CONGRESS INC                   700
WASHINGTON STATE UNIVERSITY                          492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC      408
PTA TEXAS CONGRESS                                   368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC        331
ALPHA PHI SIGMA                                      313
Name: count, dtype: int64

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, columns=['NAME', 'AFFILIATION','CLASSIFICATION','USE_CASE','ORGANIZATION','SPECIAL_CONSIDERATIONS','APPLICATION_TYPE','INCOME_AMT'], dtype='int')
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_Other,NAME_PARENT BOOSTER USA INC,NAME_PTA TEXAS CONGRESS,NAME_SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC,NAME_TOPS CLUB INC,...,APPLICATION_TYPE_T6,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,5000,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,108590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,1,5000,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,6692,1,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [14]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL']
X = application_df.drop(columns='IS_SUCCESSFUL')

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=24)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Compile, Train and Evaluate the Model

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_input_features = len(X_train.columns)
hidden_nodes_layer1 = 30
hidden_nodes_layer2 = 15
hidden_nodes_layer3 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=num_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 30)                1500

 dense_1 (Dense)             (None, 15)                465

 dense_2 (Dense)             (None, 10)                160

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 2136 (8.34 KB)
Trainable params: 2136 (8.34 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
# define filepath to where weights will be saved
filepath = '/content/drive/MyDrive/Deep_Learning/AlphabetSoupCharity_Optimization.h5'

# define modelcheckpoint callback to save model weights every 5 epochs
checkpoint_callback = ModelCheckpoint(filepath, save_weights_only=True, save_freq='epoch', period=5)

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [18]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=150, callbacks=[checkpoint_callback])

Epoch 1/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5600 - accuracy: 0.7174
Epoch 2/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5263 - accuracy: 0.7381
Epoch 3/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7404
Epoch 4/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5213 - accuracy: 0.7416
Epoch 5/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5199 - accuracy: 0.7437
Epoch 6/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5188 - accuracy: 0.7442
Epoch 7/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5184 - accuracy: 0.7447
Epoch 8/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5180 - accuracy: 0.7442
Epoch 9/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5173 - accuracy: 0.7446
Epoch 10/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5169 - accuracy: 0.7445
Epoch 11/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5165 - accuracy: 0.7440
Epoch 12/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5162 - accuracy: 0.7455
Epoch 13/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5160 - accuracy: 0.7470
Epoch 14/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7453
Epoch 15/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5156 - accuracy: 0.7463
Epoch 16/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5149 - accuracy: 0.7473
Epoch 17/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5149 - accuracy: 0.7462
Epoch 18/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5149 - accuracy: 0.7478
Epoch 19/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5143 - accuracy: 0.7455
Epoch 20/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7472
Epoch 21/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5143 - accuracy: 0.7471
Epoch 22/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5136 - accuracy: 0.7466
Epoch 23/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5135 - accuracy: 0.7471
Epoch 24/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7460
Epoch 25/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5134 - accuracy: 0.7470
Epoch 26/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5135 - accuracy: 0.7478
Epoch 27/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5132 - accuracy: 0.7476
Epoch 28/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5135 - accuracy: 0.7477
Epoch 29/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5127 - accuracy: 0.7481
Epoch 30/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5131 - accuracy: 0.7477
Epoch 31/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7479
Epoch 32/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5126 - accuracy: 0.7469
Epoch 33/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5124 - accuracy: 0.7478
Epoch 34/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5121 - accuracy: 0.7486
Epoch 35/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5124 - accuracy: 0.7492
Epoch 36/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5120 - accuracy: 0.7492
Epoch 37/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7481
Epoch 38/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7486
Epoch 39/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.7484
Epoch 40/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5115 - accuracy: 0.7473
Epoch 41/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5109 - accuracy: 0.7476
Epoch 42/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5111 - accuracy: 0.7484
Epoch 43/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5113 - accuracy: 0.7484
Epoch 44/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5112 - accuracy: 0.7490
Epoch 45/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5114 - accuracy: 0.7482
Epoch 46/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7480
Epoch 47/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5108 - accuracy: 0.7490
Epoch 48/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5103 - accuracy: 0.7491
Epoch 49/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5108 - accuracy: 0.7494
Epoch 50/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5107 - accuracy: 0.7488
Epoch 51/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5102 - accuracy: 0.7487
Epoch 52/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5102 - accuracy: 0.7488
Epoch 53/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5107 - accuracy: 0.7496
Epoch 54/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5104 - accuracy: 0.7484
Epoch 55/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5098 - accuracy: 0.7491
Epoch 56/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7493
Epoch 57/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5100 - accuracy: 0.7495
Epoch 58/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7488
Epoch 59/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5101 - accuracy: 0.7493
Epoch 60/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5099 - accuracy: 0.7489
Epoch 61/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5095 - accuracy: 0.7490
Epoch 62/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5098 - accuracy: 0.7490
Epoch 63/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5096 - accuracy: 0.7489
Epoch 64/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7492
Epoch 65/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5096 - accuracy: 0.7489
Epoch 66/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5095 - accuracy: 0.7495
Epoch 67/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5097 - accuracy: 0.7486
Epoch 68/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7497
Epoch 69/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5094 - accuracy: 0.7496
Epoch 70/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5094 - accuracy: 0.7496
Epoch 71/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5089 - accuracy: 0.7498
Epoch 72/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5091 - accuracy: 0.7495
Epoch 73/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5090 - accuracy: 0.7491
Epoch 74/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5089 - accuracy: 0.7500
Epoch 75/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5093 - accuracy: 0.7497
Epoch 76/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5088 - accuracy: 0.7510
Epoch 77/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5088 - accuracy: 0.7495
Epoch 78/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5087 - accuracy: 0.7502
Epoch 79/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5088 - accuracy: 0.7491
Epoch 80/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5088 - accuracy: 0.7505
Epoch 81/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5090 - accuracy: 0.7500
Epoch 82/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5087 - accuracy: 0.7500
Epoch 83/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7493
Epoch 84/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7508
Epoch 85/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7502
Epoch 86/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5085 - accuracy: 0.7497
Epoch 87/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5082 - accuracy: 0.7503
Epoch 88/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5086 - accuracy: 0.7488
Epoch 89/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7493
Epoch 90/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7510
Epoch 91/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7509
Epoch 92/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7497
Epoch 93/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5085 - accuracy: 0.7497
Epoch 94/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5080 - accuracy: 0.7496
Epoch 95/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5082 - accuracy: 0.7503
Epoch 96/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5082 - accuracy: 0.7502
Epoch 97/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5081 - accuracy: 0.7503
Epoch 98/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5083 - accuracy: 0.7493
Epoch 99/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5081 - accuracy: 0.7493
Epoch 100/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7502
Epoch 101/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5082 - accuracy: 0.7502
Epoch 102/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5072 - accuracy: 0.7509
Epoch 103/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7500
Epoch 104/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5081 - accuracy: 0.7502
Epoch 105/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5079 - accuracy: 0.7494
Epoch 106/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5073 - accuracy: 0.7503
Epoch 107/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5078 - accuracy: 0.7494
Epoch 108/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7500
Epoch 109/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5075 - accuracy: 0.7505
Epoch 110/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7508
Epoch 111/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5077 - accuracy: 0.7509
Epoch 112/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5073 - accuracy: 0.7511
Epoch 113/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5076 - accuracy: 0.7499
Epoch 114/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5076 - accuracy: 0.7504
Epoch 115/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7510
Epoch 116/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5073 - accuracy: 0.7504
Epoch 117/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7501
Epoch 118/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5072 - accuracy: 0.7496
Epoch 119/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7512
Epoch 120/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5072 - accuracy: 0.7509
Epoch 121/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5076 - accuracy: 0.7504
Epoch 122/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5073 - accuracy: 0.7511
Epoch 123/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5072 - accuracy: 0.7503
Epoch 124/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7509
Epoch 125/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7506
Epoch 126/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5074 - accuracy: 0.7507
Epoch 127/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5071 - accuracy: 0.7514
Epoch 128/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5077 - accuracy: 0.7492
Epoch 129/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5072 - accuracy: 0.7511
Epoch 130/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5067 - accuracy: 0.7498
Epoch 131/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5069 - accuracy: 0.7509
Epoch 132/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7514
Epoch 133/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7516
Epoch 134/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7500
Epoch 135/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7508
Epoch 136/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5070 - accuracy: 0.7509
Epoch 137/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7509
Epoch 138/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5070 - accuracy: 0.7510
Epoch 139/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5070 - accuracy: 0.7509
Epoch 140/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5071 - accuracy: 0.7504
Epoch 141/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7511
Epoch 142/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7507
Epoch 143/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5069 - accuracy: 0.7514
Epoch 144/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5066 - accuracy: 0.7509
Epoch 145/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5064 - accuracy: 0.7516
Epoch 146/150
804/804 [==============================] - 1s 2ms/step - loss: 0.5064 - accuracy: 0.7512
Epoch 147/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5067 - accuracy: 0.7495
Epoch 148/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5065 - accuracy: 0.7502
Epoch 149/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5063 - accuracy: 0.7511
Epoch 150/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5067 - accuracy: 0.7512

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5293 - accuracy: 0.7410 - 486ms/epoch - 2ms/step
Loss: 0.529297411441803, Accuracy: 0.7409912347793579

In [21]:
# Export our model to HDF5 file
nn.save(filepath)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(